// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijtolcrpwuhowmxdkhna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdG9sY3Jwd3Vob3dteGRraG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDMzNzgsImV4cCI6MjA2NTUxOTM3OH0.hHf2fGVv8rP97T70X3CUG8cP5zOFD3o81QiagThaJDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);